### ISSUE TITLE
High cpu used!

### ISSUE THREAD

**Issue by lionnner** [tib/ProgressNode#5]
just a progressNode, in device 40% cpu!?

**Comment by tib** [comment]
What kind of device, os, xcode, swift version are you using? 
Can you send me a sample project?

**Comment by lionnner** [comment]
Hi:
i just use in simple demo.
![Uploading 24D82A75-F61A-4835-96AF-2EBF7CD49B22.png…]()
![Uploading B1FB9A35-D79D-43B5-A10B-1BB84E5515DE.png…]()

Thx.

**Comment by tib** [comment]
In which method is this function?

**Comment by lionnner** [comment]
override func didMove(to view: SKView)

**Comment by tib** [comment]
I'll investigate this issue, thx for the details.

**Comment by lionnner** [comment]
Anyway thx very much.
I try to use OC to set my custom spriteNode, when i use SKShapeNode, the cpu high to 35%!
the same method with you. Is SpriteKit bug?

like this:

   _timeNode = [SKShapeNode node];

- (void)updateProgress:(CGFloat)progress
{

    CGFloat endAngle = M_PI *0.5 - progress *(2* M_PI);
    _timeNode.path = [UIBezierPath bezierPathWithArcCenter:CGPointZero
                                                    radius:self.size.width/2 - 2
                                                startAngle:M_PI *0.5
                                                  endAngle:endAngle
                                                 clockwise:YES].CGPath;
    
}
