### ISSUE TITLE
I can't self.addChild

### ISSUE THREAD

**Issue by EricCheng2222** [tib/ProgressNode#6]
Hi, I am new to swift.
I cannot self.addChild inside "override func viewDidLoad()"
and I don't know how to fix it

**Comment by tib** [comment]
Hi,

that's true, because UIViewControllers don't have addChild methods. 

You should read [SpriteKit reference](https://developer.apple.com/documentation/spritekit) first, or get some basic idea about how to make 2d games/apps using SpriteKit.
